text_to_id_lable_map = {
    'Company': '0',
    'Educational Institution': '1',
    'Artist': '2',
    'Athlete': '3',
    'OfficeHolder': '4',
    'MeanOfTransportation': '5',
    'Building': '6',
    'NaturalPlace': '7',
    'Village': '8',
    'Animal': '9',
    'Plant': '10',
    'Album': '11',
    'Film': '12',
    'WrittenWork': '13',
}

id_to_text_lable_map = {
    0: 'Company',
    1: 'Educational Institution',
    2: 'Artist',
    3: 'Athlete',
    4: 'OfficeHolder',
    5: 'MeanOfTransportation',
    6: 'Building',
    7: 'NaturalPlace',
    8: 'Village',
    9: 'Animal',
    10: 'Plant',
    11: 'Album',
    12: 'Film',
    13: 'WrittenWork',
},